version: '3'

dotenv: ['.env']

vars:
  sql_migrate_version: v1.5.2
  sql_c_version: v1.19.1

env:
  DOCKER_BUILDKIT: "1"

tasks:
  default:
    - go run .

  single-test:
    cmds:
      - go test --count=1 -v {{.CLI_ARGS}}

  gen:
    cmds:
      - buf generate