// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: deleteme.sql

package query

import (
	"context"
)

const deleteMe = `-- name: DeleteMe :one
select 1
`

func (q *Queries) DeleteMe(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, deleteMe)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
